  # environment variables
environment:
  path_to_sln: src/MonoDroid.ViewLifecycleManager.sln 
skip_tags: true
install:
  - choco install gitversion.portable -pre -y
  - cinst gitlink -version 2.4.1 -y
image: Visual Studio 2017 
assembly_info:
  patch: false
configuration:
  - Release
before_build:
- ps: gitversion /l console /output buildserver
#- cmd: msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_NuGetVersion%
- cmd: nuget restore "src/MonoDroid.ViewLifecycleManager/MonoDroid.ViewLifecycleManager.csproj" -PackagesDirectory "src/packages"
build:
  project: '%path_to_sln%'
  verbosity: minimal
after_build:
- cmd: gitlink . -u https://github.com/%APPVEYOR_REPO_NAME% -b %APPVEYOR_REPO_BRANCH% -s %APPVEYOR_REPO_COMMIT% -f %path_to_sln%
- cmd: nuget pack "src/MonoDroid.ViewLifecycleManager/MonoDroid.ViewLifecycleManager.nuspec" -Properties "configuration=release;version=%GitVersion_NuGetVersion%"
# - cmd: msbuild %path_to_sln% /t:Pack /p:PackageVersion=%GitVersion_NuGetVersion%
artifacts:
- path: /Dazinator.MonoDroid.*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*Dazinator\.MonoDroid\..*nupkg/